org: mateoismael
service: json-diagram-generator

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 60
  region: us-east-1
  iam:
    role: arn:aws:iam::111097882274:role/LabRole

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  generate-diagram:
    handler: lambda_handler.lambda_handler
    events:
      - http:
          path: /generate-diagram
          method: post
          cors: true
          integration: lambda-proxy
    layers:
      - arn:aws:lambda:us-east-1:254780740814:layer:graphvizlayer:1
